# For the sake of security, please change database stuff when actually running
version: "3.7"

services: 
  app:
    container_name: app
    image: miriondb
    build:
      context: .
      dockerfile: Dockerfile
    command: ["mirion"]
    ports:
      - 5500:5500
    environment: 
      DATABASE_URL: postgresql://miriondb:kotohoops@db/theater
      ASSETS_HOST: theater
      ASSETS_PORT: 5501
    depends_on: 
      - "db"
  db:
    image: postgres:13.4-alpine
    volumes: 
      - theater-db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: miriondb
      POSTGRES_PASSWORD: kotohoops
      POSTGRES_DB: theater
  theater:
    container_name: theater
    image: miriondb
    volumes:
      - theater-cache:/app/theater/cache/
    build:
      context: .
      dockerfile: Dockerfile
    command: ["theater"]
    ports:
      - 8000:8000
    expose: 
      - 5501
    environment: 
      ROCKET_DATABASES: '{theater={url="postgresql://miriondb:kotohoops@db/theater"}}'
      ASSETS_HOST: "0.0.0.0"
      ASSETS_PORT: 5501
    depends_on: 
      - "db"

volumes:
   theater-db:
   theater-cache: