"""empty message

Revision ID: 2f6bf0ad86bb
Revises: 
Create Date: 2021-11-19 23:27:01.993865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6bf0ad86bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'card', 'event', ['event_id'], ['id'])
    op.alter_column('event', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('event', 'db_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('db_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('event', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'card', type_='foreignkey')
    # ### end Alembic commands ###
