"""empty message

Revision ID: bec99c291420
Revises:
Create Date: 2020-11-15 17:13:29.201421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec99c291420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
                    sa.Column('db_id', sa.Integer(), autoincrement=True, 
                              nullable=False),
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('idol_id', sa.Integer(), nullable=True),
                    sa.Column('card_name', sa.Text(), nullable=True),
                    sa.Column('rarity', sa.Integer(), nullable=True),
                    sa.Column('idol_type', sa.Integer(), nullable=True),
                    sa.Column('ex_type', sa.Integer(), nullable=True),
                    sa.Column('release', sa.DateTime(), nullable=True),
                    sa.Column('skill', sa.Text(), nullable=True),
                    sa.Column('skill_id', sa.Integer(), nullable=True),
                    sa.Column('center_skill', sa.Text(), nullable=True),
                    sa.Column('vocal', sa.Integer(), nullable=True),
                    sa.Column('visual', sa.Integer(), nullable=True),
                    sa.Column('dance', sa.Integer(), nullable=True),
                    sa.Column('life', sa.Integer(), nullable=True),
                    sa.Column('awake_vocal', sa.Integer(), nullable=True),
                    sa.Column('awake_visual', sa.Integer(), nullable=True),
                    sa.Column('awake_dance', sa.Integer(), nullable=True),
                    sa.Column('card_url', sa.Text(), nullable=True),
                    sa.Column('bg_url', sa.Text(), nullable=True),
                    sa.Column('awake_card_url', sa.Text(), nullable=True),
                    sa.Column('awake_bg_url', sa.Text(), nullable=True),
                    sa.Column('costume', sa.Text(), nullable=True),
                    sa.Column('b_costume', sa.Text(), nullable=True),
                    sa.Column('r_costume', sa.Text(), nullable=True),
                    sa.Column('icon', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('db_id')
                    )
    op.create_index(op.f('ix_card_card_name'), 'card', ['card_name'], 
                    unique=False)
    op.create_index(op.f('ix_card_ex_type'), 'card', ['ex_type'], unique=False)
    op.create_index(op.f('ix_card_idol_id'), 'card', ['idol_id'], unique=False)
    op.create_index(op.f('ix_card_idol_type'), 'card', ['idol_type'], 
                    unique=False)
    op.create_index(op.f('ix_card_rarity'), 'card', ['rarity'], unique=False)
    op.create_index(op.f('ix_card_release'), 'card', ['release'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_release'), table_name='card')
    op.drop_index(op.f('ix_card_rarity'), table_name='card')
    op.drop_index(op.f('ix_card_idol_type'), table_name='card')
    op.drop_index(op.f('ix_card_idol_id'), table_name='card')
    op.drop_index(op.f('ix_card_ex_type'), table_name='card')
    op.drop_index(op.f('ix_card_card_name'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
